### ISSUE TITLE
Pipeline support?

### ISSUE THREAD

**Issue by owenhaynes** [jenkinsci/google-storage-plugin#20]
Will this support pipeline anytime soon, or can some one point me in the correct direction and will modify and push back, i am no java expert.

**Comment by tleahygoogle** [comment]
I'm also interested in getting pipelines support in this. Right now I'm having to make sh calls to gsutil.

**Comment by stefanbuck** [comment]
@laurentgo is something holding you back from opening the PR?

**Comment by laurentgo** [comment]
I simply didn't have time to actually test it.

**Comment by stefanbuck** [comment]
Testing in terms of actually using it or unit tests? I could help with the first one

**Comment by laurentgo** [comment]
Testing in terms of actually using it: it didn't have the opportunity to set up a test instance with the plugin and verify it uploads from a pipeline script (and that non pipeline use case still works too).

**Comment by stefanbuck** [comment]
Is a public accessible Jenkins instance needed in order to get this PR approved or are you talking about a test instance for your own testing purposes? Sorry, I'm not familiar with the process of creating a Jenkins plugin. Therefore one more question, could you provide me a build artefact. a jar file or so which I can install on Jenkins? That would be super helpful for me.

**Comment by laurentgo** [comment]
I was talking creating my own test instance before submitting a PR. I know that reviewers/commiters time is scarce, and so I didn't want to push something which is not working (which I don't know).

I created a release on my own repo with the plugin attached to it: https://github.com/laurentgo/google-storage-plugin/releases/tag/0.14-pipeline-support, just so you can test, but it's only temporary.

**Comment by stefanbuck** [comment]
@laurentgo the plugin still works in a Freestyle project. I added three scenarios for 
- Bucket with expiring elements
- Build Log upload
- Classic upload 

![](https://user-images.githubusercontent.com/1393946/28663990-3a97f298-72bf-11e7-8532-aa6f3fd8c644.png)

That's my job configuration https://gist.github.com/stefanbuck/07121c36436ff261be604ecc83dc3c8e

Regarding the pipeline, I have to admit that I have no clue how to call the plugin from groovy script. I looked at other plugins and try several ways, but nothing worked out. @laurentgo if you could provide me an example config that would be very helpful.

**Comment by laurentgo** [comment]
did you try the pipeline snippet generator? `http://<jenkins url>/job/<jobname>/pipeline-syntax/`

**Comment by stefanbuck** [comment]
What there is a snippet generator, this is great! Thanks for sharing. 

It produces the following snippet:

```
step google-storage(credentialsId: 'gcp-cred', uploads: [<object of type com.google.jenkins.plugins.storage.ClassicUpload>])
```

Even if I tick `For failed jobs?` or `Share Publicly?` the snipped will be the same.

**Comment by laurentgo** [comment]
so it's not working for now I guess...

**Comment by agoulti** [comment]
I've added pipeline support for the Classic Upload Step. It has just been merged to master.
I think a Classic Upload Step is the only thing that really makes sense to port, but let me know if there's more functionality you'd like to see in pipeline.

**Comment by mkroutikov** [comment]
@agoulti Could you explain how to use this plugin in pipeline DSL?
A sample snippet would help.

**Comment by agoulti** [comment]
I've just done a release, so the changes should be live within about 8 hours.

Here's a simple pipeline that demonstrates the usage:
node {
    stage('Build') {
        sh "echo World > test.txt"
        googleStorageUpload bucket: 'gs://my_bucket/path/', 
                 credentialsId: 'credentials', pattern: 'test.txt', showInline: true
    }
}

The step is included in the snippet generator, so you can click on Pipeline Syntax and choose googleStorageUpload to use the UI to build the command.
