### ISSUE TITLE
Credentials loaded on remote agent fails

### ISSUE THREAD

**Issue by wnagele** [jenkinsci/google-storage-plugin#21]
Credentials for a remote agent are incorrectly loaded inside the remote call. This results in the following exception:

> ERROR: Build step failed with exception
> com.google.jenkins.plugins.credentials.oauth.GoogleRobotPrivateKeyCredentials$AccountIdNotSetException
>     at com.google.jenkins.plugins.credentials.oauth.GoogleRobotPrivateKeyCredentials.getUsername(GoogleRobotPrivateKeyCredentials.java:152)
>     at com.google.jenkins.plugins.credentials.oauth.RemotableGoogleCredentials.<init>(RemotableGoogleCredentials.java:54)
>     at com.google.jenkins.plugins.credentials.oauth.GoogleRobotCredentials.forRemote(GoogleRobotCredentials.java:204)
>     at com.google.jenkins.plugins.storage.AbstractUpload.performUploads(AbstractUpload.java:413)
>     at com.google.jenkins.plugins.storage.AbstractUpload.access$000(AbstractUpload.java:101)
>     at com.google.jenkins.plugins.storage.AbstractUpload$1.call(AbstractUpload.java:367)
>     at com.google.jenkins.plugins.storage.AbstractUpload$1.call(AbstractUpload.java:364)
>     at hudson.remoting.UserRequest.perform(UserRequest.java:153)
>     at hudson.remoting.UserRequest.perform(UserRequest.java:50)
>     at hudson.remoting.Request$2.run(Request.java:332)
>     at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at hudson.remoting.Engine$1$1.run(Engine.java:85)
>     at java.lang.Thread.run(Thread.java:745)
>     at ......remote call to jenkins-slave-395f7dbfa981b(Native Method)
>     at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
>     at hudson.remoting.UserResponse.retrieve(UserRequest.java:253)
>     at hudson.remoting.Channel.call(Channel.java:781)
>     at hudson.FilePath.act(FilePath.java:1102)
>     at com.google.jenkins.plugins.storage.AbstractUpload.initiateUploadsAtWorkspace(AbstractUpload.java:363)
>     at com.google.jenkins.plugins.storage.AbstractUpload.perform(AbstractUpload.java:182)
>     at com.google.jenkins.plugins.storage.GoogleCloudStorageUploader.perform(GoogleCloudStorageUploader.java:109)
>     at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
>     at hudson.model.Build$BuildExecution.post2(Build.java:185)
>     at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
>     at hudson.model.Run.execute(Run.java:1766)
>     at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
>     at hudson.model.ResourceController.execute(ResourceController.java:98)
>     at hudson.model.Executor.run(Executor.java:410)

**Comment by wnagele** [comment]
Ping @astroilov - any chance to get this released with the PR merged? Currently running our own build. Not optimal.

**Comment by wnagele** [comment]
*ping*

**Comment by akbertram** [comment]
:+1:  Encountered this error as well. I was able to build my own version with the changes above and can confirm that they resolve the problem.

**Comment by wnagele** [comment]
@akbertram - if you feel like adopting this plugin you could follow the process (https://wiki.jenkins-ci.org/display/JENKINS/Adopt+a+Plugin) and get this resolved.
