### ISSUE TITLE
File pattern field is replicated for file path in GCS

### ISSUE THREAD

**Issue by 0mega** [jenkinsci/google-storage-plugin#4]
Steps to reproduce:

1) Add Classic Upload
2) Set "File Pattern" to `target/tmp/build/my_file.txt`
3) Set "Storage Location" to "gs://my_bucket_name

When the plugin uploads the artifact, the resulting artifact location is:
`my_bucket_name/target/tmp/build/my_file.txt`

The expectation here is to have the file at the following location:
`my_bucket_name/my_file.txt`

In order to keep backward compatibility, the plugin could have a checkbox "Discard file path" unchecked by default.
Whenever this checkbox is checked it would discard the file path and upload the file to the path given in "Storage Location"

**Comment by katrielt** [comment]
+1 for this one. Can't use the plugin at it's current state.

**Comment by astroilov** [comment]
Added option to strip path prefix as of version 0.9.
