### ISSUE TITLE
Google cloud plugins not working on Windows Environment

### ISSUE THREAD

**Issue by craigdbarber** [jenkinsci/google-storage-plugin#54]
I am facing issue with running Google cloud storage plugin where the plugin is working fine with Linux environments but throwing error 403 un-authorized on windows with the same service credentials private file

**Comment by craigatgoogle** [comment]
Migrated from: https://issues.jenkins-ci.org/browse/JENKINS-46411

**Comment by stephenashank** [comment]
After testing this plugin using windows agents I'm inclined to think this is related to the windows permissions errors that were resolved in https://github.com/jenkinsci/google-oauth-plugin/pull/19
