### ISSUE TITLE
Unable to save configuration changes

### ISSUE THREAD

**Issue by craigdbarber** [jenkinsci/google-storage-plugin#55]
I have recently started working with Jenkins Google cloud storage plugin. I have configured everything which is required for uploading my files to Google cloud storage. For the first time, I am able to upload files. But when I am trying to change the configurations and apply the changes, Jenkins is raising an issue. 

javax*.servlet.ServletException: java.lang.RuntimeException: Failed to serialize hudson.model.Project#builders for class hudson.model.FreeStyleProject*

**Comment by craigatgoogle** [comment]
[stacktrace](https://issues.jenkins-ci.org/secure/attachment/39414/issue.PNG)

**Comment by craigatgoogle** [comment]
Migrated from: https://issues.jenkins-ci.org/browse/JENKINS-46410

**Comment by stephenashank** [comment]
As I'm unable to reproduce this, and we've recently made changes to the serialization of the build steps, I'm considering this fixed given the age of the issue.
