### ISSUE TITLE
Enable to specify file metadata on upload

### ISSUE THREAD

**Issue by craigdbarber** [jenkinsci/google-storage-plugin#56]
When uploading files we need to allow to specify metadata associated with them.

For example if you have a text file you want to associate text/plain as its Content-Type, otherwise the browser will download the file to the disk instead of displaying it.

**Comment by craigatgoogle** [comment]
Migrated from: https://issues.jenkins-ci.org/browse/JENKINS-25621

**Comment by stephenashank** [comment]
This is possible with the Show Inline feature, resolved in #12
