### ISSUE TITLE
Please add option to remove prefix from local path when performing Classic Upload

### ISSUE THREAD

**Issue by craigdbarber** [jenkinsci/google-storage-plugin#57]
E.g. local file is Build/target/web/result.txt
Upload to gs://my-cloud

The filename in the cloud is "Build\target\web\result.txt"

The desired filename in the cloud is "result.txt"

Another plugin which handles this is the Flexible Publish plugin which has an additional field 'remove prefix' which will be removed prior to upload, so we could specify "Build/target/web" in this field to get the desired behaviour.

https://wiki.jenkins-ci.org/display/JENKINS/Flexible+Publish+Plugin

Please also note that ideally the path folder separator would be platform independent. I.e. we specify "Build/target/web" and this will work on Windows and Linux based slaves.

Options

**Comment by craigatgoogle** [comment]
Migrated from: https://issues.jenkins-ci.org/browse/JENKINS-23670

**Comment by stephenashank** [comment]
Issue from 2015, this was resolved in #27 with the "strip path prefix" option
