### ISSUE TITLE
For Classic Upload it is not possible to use a folder within a bucket

### ISSUE THREAD

**Issue by craigdbarber** [jenkinsci/google-storage-plugin#58]
Local file local_file.txt
Specify remote path like: gs://my-bucket/my-folder

The file gets added under my-bucket with filename "my-folder\local_file.txt" and not added to my-folder as intended.

Folders do work with Build Log Upload

**Comment by craigatgoogle** [comment]
Migrated from: https://issues.jenkins-ci.org/browse/JENKINS-23669

**Comment by stephenashank** [comment]
Closing because this was originally filed in 2014 and the files I've created in testing have been working with folders.
