### ISSUE TITLE
Working with Environment Variables

### ISSUE THREAD

**Issue by lo-ronk11** [jenkinsci/google-storage-plugin#69]
Hello,

This may just be a syntax error on my side but I am having issues with the GCS plugin in terms of being able to output environment variables in my GCS upload.

For example, I will have a build pipeline that runs my build / creates my artifacts but when I try to dump them using:

stage('gcs-upload') {
        steps {
            googleStorageUpload bucket: 'gs://bucket-name/$JOB_NAME-$BUILD_ID, credentialsId: '<gcs-creds>', pattern: '*.img'
}

I unfortunately will just get a folder within my bucket called '$JOB_NAME-$BUILD_ID/'.

I have tried a few different syntax's included ${JOB_NAME}-${BUILD_ID} and also (${JOB_NAME})-(${BUILD_ID}) along with experimenting with double and single quotes.  

I also have ensured that I added the step as part of my build phase in Jenkins as I do not believe the environment variables carry over to the post build phases.  

Is there something simple I am doing wrong here?  

Thank you in advance for your help!

**Comment by stephenashank** [comment]
The proper syntax to use would be `"gs://bucket-name/${JOB_NAME}-${BUILD_ID}"`. See this [Jenkinsfile](https://github.com/craigatgoogle/cloudbees-days-seattle-demo/blob/master/Jenkinsfile) for some examples of using environment variables in the pipeline with a ClassicUploadStep.
Environment variables that are used as part of a larger string use the `${ENV_VAR_NAME}` syntax within the a double quoted string. Environment variables that are used directly as the entire argument use the `env.ENV_VAR_NAME` syntax without quotes.

Let me know if you need further help.

**Comment by lo-ronk11** [comment]
Yup, it was the double quotes around the bucket name ("gs://bucket) plus the brackets that fixed it.  Thank you so much for the help / example!
