### ISSUE TITLE
add option to disable setting Content-Disposition on build log

### ISSUE THREAD

**Issue by ixdy** [jenkinsci/google-storage-plugin#7]
The uploaded build log has metadata added, setting `Content-Disposition` to something like
`attachment; filename="build-log.txt"; filename*=UTF-8''build-log.txt`.

As a result, trying to view this file through https://storage.cloud.google.com/ results in the build log being downloaded, rather than shown in the browser window.

Given that the build log is entirely text, it'd be nice to have a way to show it inline instead.

**Comment by noamtcohen** [comment]
I have a similar situation where I'm hosting a static website and after the classic upload all files get a metadata that causes my .html files to be downloaded rather then viewed in the browser.
also it would be nice if a sync option could be preformed where files not in the commit would be deleted from the bucket.

**Comment by noamtcohen** [comment]
@ixdy I created a fork that solves this problem and submitted a pull request:
https://github.com/noamtcohen/google-storage-plugin
All you have to do is compile and install the hpi file in the advance tab in the plugin management.

**Comment by znorris** [comment]
It would be nice if these changes were pulled. As it stands the plugin is still breaking hosting static webpages in a bucket. Also metadata is being added that shows the git repo which I'd prefer not to have users see.

**Comment by noamtcohen** [comment]
@znorris  did you test @ixdy commit?
